config/routes.rb
Rails.application.routes.draw do
  root "ideas#index"
  resources :prompts do
    resources :reply
    resources :detail
    post 'ask_ai', to: 'prompts#ask_with_embeddings'
  end
  post 'prompts/resemble_callback', to: 'prompts#async_callback_resemble'

  get 'ideas', to: "ideas#index"
  post 'ideas', to: "ideas#create"
  post 'ideas/ask_ai', to: 'ideas#ask_ai'
  post 'ideas/send_email', to: 'ideas#send_email'
  post 'ideas/baixing/chat', to: 'ideas#baixing'
  get 'ideas/generate_shared_picture', to: 'ideas#gen_shared_picture'

end

app/models/prompt.rb
class Prompt < ApplicationRecord
  has_one :reply
  has_one :detail
  accepts_nested_attributes_for :detail, allow_destroy: true

  validates :title, presence: true, length: { minimum: 1 }
  validates :body, presence: true, length: { minimum: 5 }
end

app/controllers/prompts_controller.rb
class PromptsController < ApplicationController
  include EmbeddingProcess
  skip_before_action :verify_authenticity_token, only: [:async_callback_resemble]

  def index
    @prompts = Prompt.all
  end

  def show 
    @prompt = Prompt.find(params[:id])
  end

  def new
    @prompt = Prompt.new
  end

  def create
    @prompt = Prompt.new(prompt_params)
    if @prompt.save
      redirect_to @prompt
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @prompt = Prompt.find(params[:id])
  end

  def update
    @prompt = Prompt.find(params[:id])
    if (@prompt.detail != nil && prompt_params.has_key?(:detail_attributes))
      @prompt.detail.update(prompt_params[:detail_attributes])
    end
    if @prompt.update(title: prompt_params[:title], body: prompt_params[:body])
      redirect_to @prompt
    else
      puts "update error; redirect to edit"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy 
    @prompt = Prompt.find(params[:id])
    if (@prompt.detail != nil)
      @prompt.detail.destroy
    end
    if (@prompt.reply != nil)
      @prompt.reply.destroy
    end
    @prompt.destroy

    redirect_to root_path, status: :see_other
  end

  def ask_ai
    # this route was replaced by ask_ai_with_embedding
    @prompt = Prompt.find(params[:prompt_id])  # need a prompt_id
    body = params[:prompt][:body]
    @prompt.update(body: body)
    ai_result = get_completion_ai(body +". your answer is:")
    ai_result = ai_result[0]  # index 0 of reply array
    print "ai_result:", ai_result , "\n"
    begin 
      clip_uuid, audio_url = speak_ai(ai_result)
    rescue => e
      puts "no audio"
      audio_url = nil
    end
    print "audio url:", audio_url, "\n"
    if defined?(@prompt.reply.body)
      @prompt.reply.update(body: ai_result, radio_url: audio_url, audio_uuid: clip_uuid)
      puts "update prompt's reply"
    else
      @prompt.reply = Reply.new(body: ai_result, prompt: @prompt, radio_url: audio_url, audio_uuid: clip_uuid)
      @prompt.reply.save
    end

    @data = { answer: ai_result, audio_src_url: audio_url }
    render json: @data
  end

  def get_completion_ai(prompt_text)
    client = OpenAI::Client.new
    response = client.completions(
        parameters: {
            model: "text-davinci-003",
            prompt: prompt_text,
            max_tokens: 10
        })
    puts response["choices"]
    result = response["choices"].map { |c| c["text"] }
  end

  def ask_with_embeddings
    # converted from python code: lib/tasks/ask_ai_with_embedding.py
    # inplement search previous question and construct prompt including similar context by openai-embedding. 
    @prompt = Prompt.find(params[:prompt_id])  # need a prompt_id
    body = params[:prompt][:body]
    if !body.end_with?("?")
      body += "?"
    end

    previous_question = Prompt.where(body: body).first
    audio_src_url = (previous_question and previous_question.reply and previous_question.reply.radio_url)
    @prompt.update(body: body) # note a probably bug: prompt update should after at finding previous_question, or it will find itself.
    if audio_src_url
      print("previously asked and answered: " + previous_question.reply.body + " ( " + previous_question.reply.radio_url + ")")
      @prompt.reply.update(body: previous_question.reply.body, radio_url: previous_question.reply.radio_url)
      render json: {"answer": previous_question.reply.body , "audio_src_url": audio_src_url, "audio_uuid": previous_question.reply.audio_uuid }
      return 
    end
    # can't find previous question so create new by asking GPT
    exampleQA = ExampleQA.new(header=HEADER, list_QA=LIST_QA)
    df = PageFrame.new(BOOK_PAGES_PATH)
    document_embeddings = load_embeddings(BOOK_EMBEDDINGS_PATH)
    answer, context = answer_query_with_context(body, df, document_embeddings, exampleQA, max_tokens=10)
    audio_uuid = speak_ai(answer)

    print("new asked and answer:" + answer + "(" + audio_uuid + ")")
    if @prompt.reply == nil
      @prompt.reply = Reply.new(body: answer, audio_uuid: audio_uuid)
      @prompt.save
    else
      @prompt.reply.update(body: answer, audio_uuid: audio_uuid )
    end

    render json: {"answer": @prompt.reply.body , "audio_uuid": audio_uuid }
  end

  def speak_ai(text)
    # create audio sounds by resemble.ai, need sync response but async now because of no money...
    require 'resemble'
    Resemble.api_key = ENV['RESEMBLE_API_TOKEN']
    project_uuid = ENV['RESEMBLE_PROJECT_UUID']
    voice_uuid = ENV['RESEMBLE_VOICE_UUID']
    callback_uri = ENV['DEPLOY_ADDRESS']+'/prompts/resemble_callback'
    callback_uri = "https://webhook.site/c90b6bf1-de09-4d83-8d4e-73ee047838cb"
    response = Resemble::V2::Clip.create_async(
      project_uuid,
      voice_uuid,
      callback_uri,
      text,
      title: nil,
      sample_rate: nil,
      output_format: nil,
      precision: nil,
      include_timestamps: nil,
      is_public: nil,
      is_archived: nil
    )
    print("create async audio ", response["success"] ? "succeed!" : response["message"])
    clip_uuid = (response["success"] ? response['item']['uuid'] : "")
    return clip_uuid
  end

  def async_callback_resemble
    clip_uuid = params[:id]
    audio_src_url = params[:url]
    reply = Reply.where(audio_uuid: clip_uuid).first
    if reply != nil
      reply.update(radio_url: audio_src_url) # update reply record
      puts "resemble callback async! update audio_url"
    end
    ActionCable.server.broadcast("voice_#{clip_uuid}", { "audio_src_url": audio_src_url })
    render json: {"audio_src_url": audio_src_url }, status: :ok
  end

  private
    def prompt_params
      # note that initialize using attributes of params
      params.require(:prompt).permit(:title, :body,
       detail_attributes: [:imgname, :imglink, :description, :alter_questions])
    end
end

app/helpers/prompts_helper.rb
module PromptsHelper
end

app/views/prompts/_form.html.erb
<%= form_with model: prompt do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% prompt.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% prompt.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  
  <div>
    <%= form.fields_for :detail_attributes, prompt.detail do |detail_form| %>
      <%= detail_form.label "img name: " %> <br>
      <%= detail_form.text_field :imgname, value: "godthemselves.png" %>
      <br>
      <%= detail_form.label "img link: " %> <br>
      <%= detail_form.text_field :imglink, value: "https://book.douban.com/subject/26264967/" %>
      <br>
      <%= detail_form.label "description: " %> <br>
      <%= detail_form.text_area :description, size: "100*10",
      value: "This is an experiment in using AI to make my book's content more accessible. Ask a question and AI'll answer it in real-time:" %>
      <br>
      <%= detail_form.label "alter questions: (splited by +) " %> <br>
      <%= detail_form.text_area :alter_questions, size: "100*10",
      value: "who's Elon Mask?+How to cure after relationship broken+I'm sad" %>
      <br>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/prompts/edit.html.erb
<h1> Edit Prompt </h1>

<%= render "form", prompt: @prompt %>

app/views/prompts/index.html.erb
<h1>Questions Lists</h1>

<ul>
  <% @prompts.each do |prompt| %>
    <li>
      <%= link_to prompt.title, prompt %>
    </li>
  <% end %>
</ul>

<%= link_to "New Question", new_prompt_path %>

app/views/prompts/new.html.erb
<h1> New Prompt </h1>

<%= render "form", prompt: @prompt %>

app/views/prompts/show.html.erb
<%= stylesheet_link_tag 'askmybook', media: 'all', 'data-turbolinks-track': 'reload' %>
<body>
<%= javascript_include_tag "jquery-3.6.3.min.js" %>
<%= javascript_include_tag "askmybook.js" %>

<div class='header'>
  <div class='logo'>
    <% detail_existed=(@prompt.detail != nil) %>
    <a href=<%= detail_existed ? @prompt.detail.imglink : "https://book.douban.com/"  %>>
    <%= image_tag detail_existed ? @prompt.detail.imgname : "godthemselves.png" %>
    </a>
    <h1><%= @prompt.title %></h1>
  </div>
</div>


<div class="main">
<p class="credits"><%= detail_existed ? @prompt.detail.description : " " %></p>
<%= form_with model: @prompt , url: "#{@prompt.id}/ask_ai", method: "post", remote: true do |form| %>
  <%= form.text_area :body , id: "prompt_body" %><br>
  <% @prompt.errors.full_messages_for(:body).each do |message| %>
    <div><%= message %></div>
  <% end %>
  <div class="buttons">
    <!-- ask button should submit first and then call action-url -->
    <%= button_tag "Ask question", id:"ask-button" %>
    <!-- lucky button will call-event ask-button, but dont submit itself. so, type should setted 'button' -->
    <%= button_tag "I'm feeling lucky", type:"button", id: "lucky-button", style:"background: #eee; border-color: #eee; color: #444;",
     onclick:"click_lucky('#{escape_javascript(@prompt.detail.alter_questions)}')" %>
  </div>
<% end %>

<p id="answer-container" class="hidden showing">
  <% if defined?(@prompt.reply.body) %>
    <strong>Answer of AI:</strong>
    <span id="answer"><%= @prompt.reply.body %></span>
    <br>
    <%= button_tag "Ask another question", id:"ask-another-button" %>
    <audio id="audio" controls autoplay src=<%= @prompt.reply.radio_url %>>
      <source src type="audio/wav">
    </audio>
  <% end %>
</p>
</div>


<footer>
  <p>
    <ul class="queue credits"> Project by <%= link_to " Elon Gong", "https://blog.elonarise.top/" %> <b> · </b>
    <%= link_to "Fork on Github", "https://github.com/virgotatus/askGPT3" %> </ul>
    <ul class="queue credits">
      <%= link_to "Edit", edit_prompt_path(@prompt) %>
      <b> | </b>
      <%= link_to "Destroy Question", prompt_path(@prompt), data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
        } %>
      <b> | </b>
      <%= link_to "Back", :prompts %>
    </ul>
  </p>
</footer>

</body>

<!-- 
// show how to insert script of javascript in html
<script>
  // Add a click event listener to the button
  setPromptButton.addEventListener("click", function() {
    // Set the value of the text field
    bodyField.value = "my New Name";
  });
</script>
-->